version: "3.9"

networks:
  devops-stack_ci_net:
    external: true   # crée-le une fois: docker network create devops-stack_ci_net

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      # HTTP and HTTPS entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # Let's Encrypt ACME configuration
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=admin@wk-archi-o23b-4-5-g5.online
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Très important: indiquer à Traefik sur quel network Docker il découvre/routte
      - --providers.docker.network=devops-stack_ci_net
      # Dashboard (expose sur 8080, à protéger si prod)
      - --api.insecure=true
      # Redirect HTTP to HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"   # Dashboard Traefik sur port 8090
    volumes:
      - ./traefik/acme.json:/letsencrypt/acme.json
      - ./traefik/dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [devops-stack_ci_net]

  gitlab:
    platform: linux/amd64
    shm_size: "1g"
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: ${GITLAB_HOST}
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8081'
        gitlab_rails['gitlab_ssh_host'] = 'localhost'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # Configuration minimale pour forcer HTTP
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        nginx['hsts_max_age'] = 0
    ports:
      - "2222:22"   # SSH GitLab
      - "8081:80"   # optionnel pour debug direct (sinon supprimer ce publish)
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=devops-stack_ci_net"

      # Désactiver le service auto par défaut
      - "traefik.http.services.gitlab.loadbalancer.server.port=0"

      # GitLab Web (HTTPS with Let's Encrypt)
      - "traefik.http.routers.gitlab.rule=Host(`${GITLAB_HOST}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.service=gitlab-web"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitlab-web.loadbalancer.server.port=80"

      # GitLab Registry (HTTPS with Let's Encrypt)
      - "traefik.http.routers.gitlab-reg.rule=Host(`${REGISTRY_HOST}`)"
      - "traefik.http.routers.gitlab-reg.entrypoints=websecure"
      - "traefik.http.routers.gitlab-reg.service=gitlab-registry"
      - "traefik.http.routers.gitlab-reg.tls=true"
      - "traefik.http.routers.gitlab-reg.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=5050"
    networks: [devops-stack_ci_net]

  jenkins:
    platform: linux/amd64
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    user: "0:0"
    environment:
      - JAVA_OPTS=-Dhudson.security.csrf.CrumbFilter.EXCLUDES=/gitlab-webhook/.*
      - JENKINS_OPTS=--prefix=/
    ports:
      - "8080:8080"   # Exposition directe de Jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=devops-stack_ci_net"
      - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOST}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks: [devops-stack_ci_net]

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
