version: "3.9"

networks:
  ci_net:
    driver: bridge

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Rediriger HTTP -> HTTPS (disabled for registry)
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # HTTPS configuration with self-signed certificates
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - --providers.docker.network=devops-stack_ci_net 
      # Tu peux garder websecure + ACME pour plus tard, mais inutile en .local
      - --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.web.address=:80 # pour debug
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/acme.json:/letsencrypt/acme.json
      - ./traefik/dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [ci_net]

  gitlab:
    platform: linux/amd64          # indispensable sur Mac Apple Silicon
    shm_size: "1g"
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: ${GITLAB_HOST}
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST}'
        gitlab_rails['gitlab_ssh_host'] = '${GITLAB_HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        registry_external_url 'https://${REGISTRY_HOST}'
        gitlab_rails['registry_enabled'] = true
        registry['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['gitlab_https'] = false 
    ports:
      - "2222:22"   # SSH GitLab (git@...:2222)
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=devops-stack_ci_net"
      # GitLab Web
      - "traefik.http.routers.gitlab-web.rule=Host(`gitlab.local`)"
      - "traefik.http.routers.gitlab-web.entrypoints=websecure"
      - "traefik.http.routers.gitlab-web.tls=true"
      - "traefik.http.routers.gitlab-web.service=gitlab-web"
      - "traefik.http.services.gitlab-web.loadbalancer.server.port=80"
      # GitLab Registry
      - "traefik.http.routers.gitlab-registry.rule=Host(`registry.gitlab.local`)"
      - "traefik.http.routers.gitlab-registry.entrypoints=websecure"
      - "traefik.http.routers.gitlab-registry.tls=true"
      - "traefik.http.routers.gitlab-registry.service=gitlab-registry"
      - "traefik.http.services.gitlab-registry.loadbalancer.server.port=5050"
    networks: [ci_net]

  jenkins:
    platform: linux/amd64
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    user: "0:0"
    environment:
      - JAVA_OPTS=-Dhudson.security.csrf.CrumbFilter.EXCLUDES=/gitlab-webhook/.*
      - JENKINS_OPTS=--prefix=/
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=devops-stack_ci_net" 
      - "traefik.http.routers.jenkins.rule=Host(`${JENKINS_HOST}`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks: [ci_net]

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
